-- Full flow create
DROP SCHEMA IF EXISTS ADVENTUREWORKS_RAW.FACT CASCADE;
DROP SCHEMA IF EXISTS ADVENTUREWORKS_RAW.LOOKUP CASCADE;
DROP SCHEMA IF EXISTS ADVENTUREWORKS_RAW.DIM CASCADE;
-- 1. Create DB and schema
CREATE DATABASE IF NOT EXISTS ADVENTUREWORKS_RAW;
USE DATABASE ADVENTUREWORKS_RAW;
CREATE SCHEMA IF NOT EXISTS CONTROL;
USE SCHEMA CONTROL;

-- 1.1. Create temp table for table in use list
-- DROP TABLE IF EXISTS TARGET_TABLE;
CREATE TEMP TABLE TARGET_TABLE (
    DATABASE_NAME STRING,
    SCHEMA_NAME   STRING,
    TABLE_NAME    STRING
);

-- 4. Insert danh sách bảng vào bảng tạm
TRUNCATE TABLE TARGET_TABLE;
INSERT INTO TARGET_TABLE (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME)
VALUES
('ADVENTUREWORKS_RAW','DIM','PERSON_PERSON')
,('ADVENTUREWORKS_RAW','DIM','PRODUCTION_PRODUCT')
,('ADVENTUREWORKS_RAW','FACT','SALES_CUSTOMER')
,('ADVENTUREWORKS_RAW','FACT','SALES_SALESORDERDETAIL')
,('ADVENTUREWORKS_RAW','FACT','SALES_SALESORDERHEADER')
,('ADVENTUREWORKS_RAW','FACT','SALES_SALESTERRITORY')
,('ADVENTUREWORKS_RAW','FACT','SALES_SPECIALOFFER')
;

-- 2 Create SP "SP_CREATE_SCHEMAS_FROM_METADATA" to auto create distinct schema in meta data file
-- CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_SCHEMAS_FROM_METADATA(
--     p_schema_name STRING,   -- schema chứa metadata table
--     p_table_name  STRING    -- metadata table name
-- )
-- RETURNS STRING
-- LANGUAGE SQL
-- EXECUTE AS OWNER
-- AS
-- $$
-- DECLARE
--     v_sql        STRING;
--     v_rs         RESULTSET;
--     v_schema     STRING;
-- BEGIN
--     ------------------------------------------------------------------
--     -- Build dynamic SQL to get distinct schema_name
--     ------------------------------------------------------------------
--     v_sql := '
--         SELECT DISTINCT schema_name
--         FROM ' || p_schema_name || '.' || p_table_name || '
--         WHERE schema_name IS NOT NULL
--     ';

--     ------------------------------------------------------------------
--     -- Execute query into RESULTSET
--     ------------------------------------------------------------------
--     v_rs := (EXECUTE IMMEDIATE :v_sql);

--     ------------------------------------------------------------------
--     -- Loop through resultset
--     ------------------------------------------------------------------
--     FOR rec IN v_rs DO
--         v_schema := rec.schema_name;

--         EXECUTE IMMEDIATE
--             'CREATE SCHEMA IF NOT EXISTS ADVENTUREWORKS_RAW.' || v_schema;
--     END FOR;

--     RETURN 'Schemas created successfully from ' || p_schema_name || '.' || p_table_name;
-- END;
-- $$;

-- 2.1. Create distinct schemas
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_SCHEMAS_FROM_METADATA(
    'ADVENTUREWORKS_RAW.CONTROL',
    'RAW_TABLE_METADATA'
);

-- 3. Create integration "s3_adventureworks_int"
-- CREATE OR REPLACE STORAGE INTEGRATION s3_adventureworks_int
--   TYPE = EXTERNAL_STAGE
--   STORAGE_PROVIDER = S3
--   ENABLED = TRUE
--   STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::593857178186:role/snowflake_s3_role'
--   STORAGE_ALLOWED_LOCATIONS = (
--     's3://adventureworks-mockup-dienpt7/adventureworks-data/raw/'
--   );

-- DESC STORAGE INTEGRATION s3_adventureworks_int; -- Update policy trust of AWS IAM role

-- 4. Create stage "AW_RAW_S3_STAGE"
-- CREATE OR REPLACE STAGE ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE
--   URL = 's3://adventureworks-mockup-dienpt7/adventureworks-data/raw/'
--   STORAGE_INTEGRATION = s3_adventureworks_int;

-- 5. Create csv format "CSV_RAW_FORMAT"
-- CREATE OR REPLACE FILE FORMAT ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
--   TYPE = CSV
--   FIELD_OPTIONALLY_ENCLOSED_BY = '"'
--   SKIP_HEADER = 1
--   NULL_IF = ('', 'NULL')
--   ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- 6. Create SP create table "SP_CREATE_TABLES_FROM_METADATA"
CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA(
    P_DATABASE STRING,
    P_SCHEMA   STRING,
    P_TABLE    STRING
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_COL_DEF STRING;
BEGIN
    /* 1. Build column definition từ metadata */
    SELECT LISTAGG(COLUMN_NAME || ' ' || DATA_TYPE, ', ')
           WITHIN GROUP (ORDER BY ORDINAL_POSITION)
    INTO :V_COL_DEF
    FROM ADVENTUREWORKS_RAW.CONTROL.RAW_TABLE_METADATA
    WHERE DATABASE_NAME = :P_DATABASE
      AND SCHEMA_NAME   = :P_SCHEMA
      AND TABLE_NAME    = :P_TABLE;

    /* 2. Create RAW table */
    EXECUTE IMMEDIATE
      'CREATE TABLE IF NOT EXISTS ' || P_DATABASE || '.' || P_SCHEMA || '.' || P_TABLE || ' (
         ' || V_COL_DEF || ',
         ROW_HASH VARCHAR, -- debug
         PK_HASH  VARCHAR -- debug
       )';

    /* 3. Create LOAD table */
    EXECUTE IMMEDIATE
      'CREATE TABLE IF NOT EXISTS ' || P_DATABASE || '.' || P_SCHEMA || '.' || P_TABLE || '_LOAD (
         ' || V_COL_DEF || ',
         _FILENAME     VARCHAR,
         _INGESTED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
       )';

    /* 4. Create HISTORY table */
    EXECUTE IMMEDIATE
      'CREATE TABLE IF NOT EXISTS ' || P_DATABASE || '.' || P_SCHEMA || '.' || P_TABLE || '_HISTORY (
         ' || V_COL_DEF || ',
         ROW_HASH       VARCHAR,
         PK_HASH        VARCHAR, -- debug PK null
         EFFECTIVE_FROM TIMESTAMP_NTZ,
         EFFECTIVE_TO   TIMESTAMP_NTZ,
         IS_CURRENT     BOOLEAN,
         IS_DELETED     BOOLEAN,
         LOAD_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
       )';

    RETURN 'TABLES created for ' || P_SCHEMA || '.' || P_TABLE;
END;
$$;

-- 6.1. Generate CALL query for "SP_CREATE_TABLES_FROM_METADATA"
-- SELECT DISTINCT
--     'CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA(''' ||
--     m.DATABASE_NAME || ''',''' ||
--     m.SCHEMA_NAME   || ''',''' ||
--     m.TABLE_NAME    || ''');' AS call_statement
-- FROM ADVENTUREWORKS_RAW.CONTROL.RAW_TABLE_METADATA m
-- JOIN TARGET_TABLE t 
--     ON m.TABLE_NAME = t.TABLE_NAME
-- ORDER BY call_statement;

-- 6.2. CALL query create table
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA('ADVENTUREWORKS_RAW','DIM','PERSON_PERSON');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA('ADVENTUREWORKS_RAW','DIM','PRODUCTION_PRODUCT');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA('ADVENTUREWORKS_RAW','FACT','SALES_CUSTOMER');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA('ADVENTUREWORKS_RAW','FACT','SALES_SALESORDERDETAIL');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA('ADVENTUREWORKS_RAW','FACT','SALES_SALESORDERHEADER');
-- CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA('ADVENTUREWORKS_RAW','FACT','SALES_SALESTERRITORY');
-- SELECT COLUMN_NAME, DATA_TYPE
-- FROM ADVENTUREWORKS_RAW.CONTROL.RAW_TABLE_METADATA
-- WHERE DATABASE_NAME = 'ADVENTUREWORKS_RAW'
--   AND SCHEMA_NAME   = 'FACT'
--   AND TABLE_NAME    = 'SALES_SALESTERRITORY';
CREATE OR REPLACE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY (
    TERRITORYID	NUMBER
    ,NAME	VARCHAR
    ,COUNTRYREGIONCODE	VARCHAR
    ,"GROUP"	VARCHAR
    ,SALESYTD	FLOAT
    ,SALESLASTYEAR	FLOAT
    ,COSTYTD	FLOAT
    ,COSTLASTYEAR	FLOAT
    ,ROWGUID	VARCHAR
    ,MODIFIEDDATE	VARCHAR
    , ROW_HASH VARCHAR
    , PK_HASH VARCHAR
);
CREATE OR REPLACE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_LOAD (
    TERRITORYID	NUMBER
    ,NAME	VARCHAR
    ,COUNTRYREGIONCODE	VARCHAR
    ,"GROUP"	VARCHAR
    ,SALESYTD	FLOAT
    ,SALESLASTYEAR	FLOAT
    ,COSTYTD	FLOAT
    ,COSTLASTYEAR	FLOAT
    ,ROWGUID	VARCHAR
    ,MODIFIEDDATE	VARCHAR
    , _FILENAME     VARCHAR
    , _INGESTED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_HISTORY (
    TERRITORYID	NUMBER
    ,NAME	VARCHAR
    ,COUNTRYREGIONCODE	VARCHAR
    ,"GROUP"	VARCHAR
    ,SALESYTD	FLOAT
    ,SALESLASTYEAR	FLOAT
    ,COSTYTD	FLOAT
    ,COSTLASTYEAR	FLOAT
    ,ROWGUID	VARCHAR
    ,MODIFIEDDATE	VARCHAR
    , ROW_HASH       VARCHAR
    , PK_HASH        VARCHAR
    , EFFECTIVE_FROM TIMESTAMP_NTZ
    , EFFECTIVE_TO   TIMESTAMP_NTZ
    , IS_CURRENT     BOOLEAN
    , IS_DELETED     BOOLEAN
    , LOAD_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_TABLES_FROM_METADATA('ADVENTUREWORKS_RAW','FACT','SALES_SPECIALOFFER');
-- DROP TABLE IF EXISTS ADVENTUREWORKS_RAW.DIM.PERSON_PERSON ; -- debug
-- DROP TABLE IF EXISTS ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_LOAD ; -- debug
-- DROP TABLE IF EXISTS ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_HISTORY ; -- debug
-- END 6.2.

-- 7. Create pipe
-- WITH col_meta AS (
--     SELECT
--         database_name,
--         schema_name,
--         table_name,

--         /* column list */
--         LISTAGG(column_name, ', ')
--             WITHIN GROUP (ORDER BY ordinal_position) AS col_list,

--         /* $1, $2, ... */
--         LISTAGG('$' || ordinal_position, ', ')
--             WITHIN GROUP (ORDER BY ordinal_position) AS select_list

--     FROM ADVENTUREWORKS_RAW.CONTROL.RAW_TABLE_METADATA
--     GROUP BY database_name, schema_name, table_name
-- )

-- SELECT
-- 'CREATE OR REPLACE PIPE ' || t.database_name || '.' || t.schema_name || '.PIPE_' || t.table_name || '_LOAD
-- AUTO_INGEST = TRUE
-- AS
-- COPY INTO ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_LOAD
-- (
--   ' || m.col_list || ',
--   _FILENAME
-- )
-- FROM (
--   SELECT
--     ' || m.select_list || ',
--     METADATA$FILENAME
--   FROM @' || t.database_name || '.CONTROL.AW_RAW_S3_STAGE/' || LOWER(t.schema_name) || '
-- )
-- FILE_FORMAT = ' || t.database_name || '.CONTROL.CSV_RAW_FORMAT
-- PATTERN = ''(?i).*' || t.table_name || '\.csv|.*' || t.table_name || '_[0-9]+_[0-9]+\.csv''
-- ON_ERROR = ''CONTINUE'';
-- ' AS CREATE_PIPE_SQL
-- FROM TARGET_TABLE t
-- JOIN col_meta m
--   ON t.database_name = m.database_name
--  AND t.schema_name   = m.schema_name
--  AND t.table_name    = m.table_name
-- ORDER BY t.schema_name, t.table_name;

-- 7.2. CREATE 
CREATE OR REPLACE PIPE ADVENTUREWORKS_RAW.DIM.PIPE_PERSON_PERSON_LOAD
AUTO_INGEST = TRUE
AS
COPY INTO ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_LOAD
(
  BUSINESSENTITYID, PERSONTYPE, NAMESTYLE, TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, SUFFIX, EMAILPROMOTION, ADDITIONALCONTACTINFO, DEMOGRAPHICS, ROWGUID, MODIFIEDDATE,
  _FILENAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    METADATA$FILENAME
  FROM @ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE/dim
)
FILE_FORMAT = ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
PATTERN = '(?i).*PERSON_PERSON.csv|.*PERSON_PERSON_[0-9]+_[0-9]+.csv'
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ADVENTUREWORKS_RAW.DIM.PIPE_PRODUCTION_PRODUCT_LOAD
AUTO_INGEST = TRUE
AS
COPY INTO ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_LOAD
(
  PRODUCTID, NAME, PRODUCTNUMBER, MAKEFLAG, FINISHEDGOODSFLAG, COLOR, SAFETYSTOCKLEVEL, REORDERPOINT, STANDARDCOST, LISTPRICE, SIZE, SIZEUNITMEASURECODE, WEIGHTUNITMEASURECODE, WEIGHT, DAYSTOMANUFACTURE, PRODUCTLINE, CLASS, STYLE, PRODUCTSUBCATEGORYID, PRODUCTMODELID, SELLSTARTDATE, SELLENDDATE, DISCONTINUEDDATE, ROWGUID, MODIFIEDDATE,
  _FILENAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25,
    METADATA$FILENAME
  FROM @ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE/dim
)
FILE_FORMAT = ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
PATTERN = '(?i).*PRODUCTION_PRODUCT.csv|.*PRODUCTION_PRODUCT_[0-9]+_[0-9]+.csv'
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ADVENTUREWORKS_RAW.FACT.PIPE_SALES_CUSTOMER_LOAD
AUTO_INGEST = TRUE
AS
COPY INTO ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_LOAD
(
  CUSTOMERID, PERSONID, STOREID, TERRITORYID, ACCOUNTNUMBER, ROWGUID, MODIFIEDDATE,
  _FILENAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7,
    METADATA$FILENAME
  FROM @ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE/fact
)
FILE_FORMAT = ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
PATTERN = '(?i).*SALES_CUSTOMER.csv|.*SALES_CUSTOMER_[0-9]+_[0-9]+.csv'
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ADVENTUREWORKS_RAW.FACT.PIPE_SALES_SALESORDERDETAIL_LOAD
AUTO_INGEST = TRUE
AS
COPY INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_LOAD
(
  SALESORDERID, SALESORDERDETAILID, CARRIERTRACKINGNUMBER, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT, LINETOTAL, ROWGUID, MODIFIEDDATE,
  _FILENAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    METADATA$FILENAME
  FROM @ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE/fact
)
FILE_FORMAT = ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
PATTERN = '(?i).*SALES_SALESORDERDETAIL.csv|.*SALES_SALESORDERDETAIL_[0-9]+_[0-9]+.csv'
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ADVENTUREWORKS_RAW.FACT.PIPE_SALES_SALESORDERHEADER_LOAD
AUTO_INGEST = TRUE
AS
COPY INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_LOAD
(
  SALESORDERID, REVISIONNUMBER, ORDERDATE, DUEDATE, SHIPDATE, STATUS, ONLINEORDERFLAG, SALESORDERNUMBER, PURCHASEORDERNUMBER, ACCOUNTNUMBER, CUSTOMERID, SALESPERSONID, TERRITORYID, BILLTOADDRESSID, SHIPTOADDRESSID, SHIPMETHODID, CREDITCARDID, CREDITCARDAPPROVALCODE, CURRENCYRATEID, SUBTOTAL, TAXAMT, FREIGHT, TOTALDUE, COMMENT, ROWGUID, MODIFIEDDATE,
  _FILENAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26,
    METADATA$FILENAME
  FROM @ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE/fact
)
FILE_FORMAT = ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
PATTERN = '(?i).*SALES_SALESORDERHEADER.csv|.*SALES_SALESORDERHEADER_[0-9]+_[0-9]+.csv'
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ADVENTUREWORKS_RAW.FACT.PIPE_SALES_SALESTERRITORY_LOAD
AUTO_INGEST = TRUE
AS
COPY INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_LOAD
(
  TERRITORYID, NAME, COUNTRYREGIONCODE, "GROUP", SALESYTD, SALESLASTYEAR, COSTYTD, COSTLASTYEAR, ROWGUID, MODIFIEDDATE,
  _FILENAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    METADATA$FILENAME
  FROM @ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE/fact
)
FILE_FORMAT = ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
PATTERN = '(?i).*SALES_SALESTERRITORY.csv|.*SALES_SALESTERRITORY_[0-9]+_[0-9]+.csv'
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE ADVENTUREWORKS_RAW.FACT.PIPE_SALES_SPECIALOFFER_LOAD
AUTO_INGEST = TRUE
AS
COPY INTO ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_LOAD
(
  SPECIALOFFERID, DESCRIPTION, DISCOUNTPCT, TYPE, CATEGORY, STARTDATE, ENDDATE, MINQTY, MAXQTY, ROWGUID, MODIFIEDDATE,
  _FILENAME
)
FROM (
  SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    METADATA$FILENAME
  FROM @ADVENTUREWORKS_RAW.CONTROL.AW_RAW_S3_STAGE/fact
)
FILE_FORMAT = ADVENTUREWORKS_RAW.CONTROL.CSV_RAW_FORMAT
PATTERN = '(?i).*SALES_SPECIALOFFER.csv|.*SALES_SPECIALOFFER_[0-9]+_[0-9]+.csv'
ON_ERROR = 'CONTINUE';

-- 8. Create statement to create SP LOAD to RAW
WITH col_meta AS (
    SELECT
        database_name,
        schema_name,
        table_name,

        /* (1) column list for INSERT */
        LISTAGG(column_name, ',\n        ')
            WITHIN GROUP (ORDER BY ordinal_position) AS insert_col_list,

        /* (2) column list for SELECT */
        LISTAGG(column_name, ',\n        ')
            WITHIN GROUP (ORDER BY ordinal_position) AS select_col_list,

        /* (3) PK_HASH expression (CASE WHEN thay FILTER) */ 
        'HASH(' || 
        LISTAGG( 
            CASE WHEN is_primary_key THEN 'TO_VARCHAR(' || column_name || ')' END, 
            ', ' ) WITHIN GROUP (ORDER BY pk_ordinal_position) || ')' AS pk_hash_expr,

    FROM ADVENTUREWORKS_RAW.CONTROL.RAW_TABLE_METADATA
    GROUP BY database_name, schema_name, table_name
)

SELECT
'CREATE OR REPLACE PROCEDURE ' || t.database_name || '.CONTROL.SP_' || t.table_name || '_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN ''No file found in LOAD table'';
    END IF;

    TRUNCATE TABLE ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || ';

    INSERT INTO ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '
    (
        ' || m.insert_col_list || ',
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        ' || m.select_col_list || ',
        HASH(' || m.select_col_list || '), -- debug
        ' || pk_hash_expr || '
    FROM ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN ''RAW refreshed from '' || V_LATEST_FILENAME;
END;
$$;
' AS CREATE_SP_SQL
FROM TARGET_TABLE t
JOIN col_meta m
  ON t.database_name = m.database_name
 AND t.schema_name   = m.schema_name
 AND t.table_name    = m.table_name
ORDER BY t.schema_name, t.table_name;

-- 8.1 CREATE SP 
CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_PERSON_PERSON_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN 'No file found in LOAD table';
    END IF;

    TRUNCATE TABLE ADVENTUREWORKS_RAW.DIM.PERSON_PERSON;

    INSERT INTO ADVENTUREWORKS_RAW.DIM.PERSON_PERSON
    (
        BUSINESSENTITYID,
        PERSONTYPE,
        NAMESTYLE,
        TITLE,
        FIRSTNAME,
        MIDDLENAME,
        LASTNAME,
        SUFFIX,
        EMAILPROMOTION,
        ADDITIONALCONTACTINFO,
        DEMOGRAPHICS,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        BUSINESSENTITYID,
        PERSONTYPE,
        NAMESTYLE,
        TITLE,
        FIRSTNAME,
        MIDDLENAME,
        LASTNAME,
        SUFFIX,
        EMAILPROMOTION,
        ADDITIONALCONTACTINFO,
        DEMOGRAPHICS,
        ROWGUID,
        MODIFIEDDATE,
        HASH(BUSINESSENTITYID,
        PERSONTYPE,
        NAMESTYLE,
        TITLE,
        FIRSTNAME,
        MIDDLENAME,
        LASTNAME,
        SUFFIX,
        EMAILPROMOTION,
        ADDITIONALCONTACTINFO,
        DEMOGRAPHICS,
        ROWGUID,
        MODIFIEDDATE), -- debug
        HASH(TO_VARCHAR(BUSINESSENTITYID), TO_VARCHAR(MIDDLENAME), TO_VARCHAR(ROWGUID))
    FROM ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN 'RAW refreshed from ' || V_LATEST_FILENAME;
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_PRODUCTION_PRODUCT_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN 'No file found in LOAD table';
    END IF;

    TRUNCATE TABLE ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT;

    INSERT INTO ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT
    (
        PRODUCTID,
        NAME,
        PRODUCTNUMBER,
        MAKEFLAG,
        FINISHEDGOODSFLAG,
        COLOR,
        SAFETYSTOCKLEVEL,
        REORDERPOINT,
        STANDARDCOST,
        LISTPRICE,
        SIZE,
        SIZEUNITMEASURECODE,
        WEIGHTUNITMEASURECODE,
        WEIGHT,
        DAYSTOMANUFACTURE,
        PRODUCTLINE,
        CLASS,
        STYLE,
        PRODUCTSUBCATEGORYID,
        PRODUCTMODELID,
        SELLSTARTDATE,
        SELLENDDATE,
        DISCONTINUEDDATE,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        PRODUCTID,
        NAME,
        PRODUCTNUMBER,
        MAKEFLAG,
        FINISHEDGOODSFLAG,
        COLOR,
        SAFETYSTOCKLEVEL,
        REORDERPOINT,
        STANDARDCOST,
        LISTPRICE,
        SIZE,
        SIZEUNITMEASURECODE,
        WEIGHTUNITMEASURECODE,
        WEIGHT,
        DAYSTOMANUFACTURE,
        PRODUCTLINE,
        CLASS,
        STYLE,
        PRODUCTSUBCATEGORYID,
        PRODUCTMODELID,
        SELLSTARTDATE,
        SELLENDDATE,
        DISCONTINUEDDATE,
        ROWGUID,
        MODIFIEDDATE,
        HASH(PRODUCTID,
        NAME,
        PRODUCTNUMBER,
        MAKEFLAG,
        FINISHEDGOODSFLAG,
        COLOR,
        SAFETYSTOCKLEVEL,
        REORDERPOINT,
        STANDARDCOST,
        LISTPRICE,
        SIZE,
        SIZEUNITMEASURECODE,
        WEIGHTUNITMEASURECODE,
        WEIGHT,
        DAYSTOMANUFACTURE,
        PRODUCTLINE,
        CLASS,
        STYLE,
        PRODUCTSUBCATEGORYID,
        PRODUCTMODELID,
        SELLSTARTDATE,
        SELLENDDATE,
        DISCONTINUEDDATE,
        ROWGUID,
        MODIFIEDDATE), -- debug
        HASH(TO_VARCHAR(PRODUCTID), TO_VARCHAR(PRODUCTSUBCATEGORYID), TO_VARCHAR(PRODUCTMODELID), TO_VARCHAR(ROWGUID))
    FROM ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN 'RAW refreshed from ' || V_LATEST_FILENAME;
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_CUSTOMER_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN 'No file found in LOAD table';
    END IF;

    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER;

    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER
    (
        CUSTOMERID,
        PERSONID,
        STOREID,
        TERRITORYID,
        ACCOUNTNUMBER,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        CUSTOMERID,
        PERSONID,
        STOREID,
        TERRITORYID,
        ACCOUNTNUMBER,
        ROWGUID,
        MODIFIEDDATE,
        HASH(CUSTOMERID,
        PERSONID,
        STOREID,
        TERRITORYID,
        ACCOUNTNUMBER,
        ROWGUID,
        MODIFIEDDATE), -- debug
        HASH(TO_VARCHAR(CUSTOMERID), TO_VARCHAR(PERSONID), TO_VARCHAR(STOREID), TO_VARCHAR(TERRITORYID), TO_VARCHAR(ROWGUID))
    FROM ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN 'RAW refreshed from ' || V_LATEST_FILENAME;
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESORDERDETAIL_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN 'No file found in LOAD table';
    END IF;

    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL;

    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL
    (
        SALESORDERID,
        SALESORDERDETAILID,
        CARRIERTRACKINGNUMBER,
        ORDERQTY,
        PRODUCTID,
        SPECIALOFFERID,
        UNITPRICE,
        UNITPRICEDISCOUNT,
        LINETOTAL,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        SALESORDERID,
        SALESORDERDETAILID,
        CARRIERTRACKINGNUMBER,
        ORDERQTY,
        PRODUCTID,
        SPECIALOFFERID,
        UNITPRICE,
        UNITPRICEDISCOUNT,
        LINETOTAL,
        ROWGUID,
        MODIFIEDDATE,
        HASH(SALESORDERID,
        SALESORDERDETAILID,
        CARRIERTRACKINGNUMBER,
        ORDERQTY,
        PRODUCTID,
        SPECIALOFFERID,
        UNITPRICE,
        UNITPRICEDISCOUNT,
        LINETOTAL,
        ROWGUID,
        MODIFIEDDATE), -- debug
        HASH(TO_VARCHAR(SALESORDERID), TO_VARCHAR(SALESORDERDETAILID), TO_VARCHAR(PRODUCTID), TO_VARCHAR(SPECIALOFFERID), TO_VARCHAR(ROWGUID))
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN 'RAW refreshed from ' || V_LATEST_FILENAME;
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESORDERHEADER_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN 'No file found in LOAD table';
    END IF;

    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER;

    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER
    (
        SALESORDERID,
        REVISIONNUMBER,
        ORDERDATE,
        DUEDATE,
        SHIPDATE,
        STATUS,
        ONLINEORDERFLAG,
        SALESORDERNUMBER,
        PURCHASEORDERNUMBER,
        ACCOUNTNUMBER,
        CUSTOMERID,
        SALESPERSONID,
        TERRITORYID,
        BILLTOADDRESSID,
        SHIPTOADDRESSID,
        SHIPMETHODID,
        CREDITCARDID,
        CREDITCARDAPPROVALCODE,
        CURRENCYRATEID,
        SUBTOTAL,
        TAXAMT,
        FREIGHT,
        TOTALDUE,
        COMMENT,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        SALESORDERID,
        REVISIONNUMBER,
        ORDERDATE,
        DUEDATE,
        SHIPDATE,
        STATUS,
        ONLINEORDERFLAG,
        SALESORDERNUMBER,
        PURCHASEORDERNUMBER,
        ACCOUNTNUMBER,
        CUSTOMERID,
        SALESPERSONID,
        TERRITORYID,
        BILLTOADDRESSID,
        SHIPTOADDRESSID,
        SHIPMETHODID,
        CREDITCARDID,
        CREDITCARDAPPROVALCODE,
        CURRENCYRATEID,
        SUBTOTAL,
        TAXAMT,
        FREIGHT,
        TOTALDUE,
        COMMENT,
        ROWGUID,
        MODIFIEDDATE,
        HASH(SALESORDERID,
        REVISIONNUMBER,
        ORDERDATE,
        DUEDATE,
        SHIPDATE,
        STATUS,
        ONLINEORDERFLAG,
        SALESORDERNUMBER,
        PURCHASEORDERNUMBER,
        ACCOUNTNUMBER,
        CUSTOMERID,
        SALESPERSONID,
        TERRITORYID,
        BILLTOADDRESSID,
        SHIPTOADDRESSID,
        SHIPMETHODID,
        CREDITCARDID,
        CREDITCARDAPPROVALCODE,
        CURRENCYRATEID,
        SUBTOTAL,
        TAXAMT,
        FREIGHT,
        TOTALDUE,
        COMMENT,
        ROWGUID,
        MODIFIEDDATE), -- debug
        HASH(TO_VARCHAR(SALESORDERID), TO_VARCHAR(CUSTOMERID), TO_VARCHAR(SALESPERSONID), TO_VARCHAR(TERRITORYID), TO_VARCHAR(BILLTOADDRESSID), TO_VARCHAR(SHIPTOADDRESSID), TO_VARCHAR(SHIPMETHODID), TO_VARCHAR(CREDITCARDID), TO_VARCHAR(CURRENCYRATEID), TO_VARCHAR(ROWGUID))
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN 'RAW refreshed from ' || V_LATEST_FILENAME;
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESTERRITORY_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN 'No file found in LOAD table';
    END IF;

    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY;

    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY
    (
        TERRITORYID,
        NAME,
        COUNTRYREGIONCODE,
        "GROUP",
        SALESYTD,
        SALESLASTYEAR,
        COSTYTD,
        COSTLASTYEAR,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        TERRITORYID,
        NAME,
        COUNTRYREGIONCODE,
        "GROUP",
        SALESYTD,
        SALESLASTYEAR,
        COSTYTD,
        COSTLASTYEAR,
        ROWGUID,
        MODIFIEDDATE,
        HASH(TERRITORYID,
        NAME,
        COUNTRYREGIONCODE,
        "GROUP",
        SALESYTD,
        SALESLASTYEAR,
        COSTYTD,
        COSTLASTYEAR,
        ROWGUID,
        MODIFIEDDATE), -- debug
        HASH(TO_VARCHAR(TERRITORYID), TO_VARCHAR(ROWGUID))
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN 'RAW refreshed from ' || V_LATEST_FILENAME;
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SPECIALOFFER_FROM_LOAD_TO_RAW()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LATEST_FILENAME STRING;
BEGIN
    SELECT MAX(_FILENAME)
    INTO :V_LATEST_FILENAME
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_LOAD;

    IF (V_LATEST_FILENAME IS NULL) THEN
        RETURN 'No file found in LOAD table';
    END IF;

    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER;

    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER
    (
        SPECIALOFFERID,
        DESCRIPTION,
        DISCOUNTPCT,
        TYPE,
        CATEGORY,
        STARTDATE,
        ENDDATE,
        MINQTY,
        MAXQTY,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH, -- debug
        PK_HASH -- debug
    )
    SELECT
        SPECIALOFFERID,
        DESCRIPTION,
        DISCOUNTPCT,
        TYPE,
        CATEGORY,
        STARTDATE,
        ENDDATE,
        MINQTY,
        MAXQTY,
        ROWGUID,
        MODIFIEDDATE,
        HASH(SPECIALOFFERID,
        DESCRIPTION,
        DISCOUNTPCT,
        TYPE,
        CATEGORY,
        STARTDATE,
        ENDDATE,
        MINQTY,
        MAXQTY,
        ROWGUID,
        MODIFIEDDATE), -- debug
        HASH(TO_VARCHAR(SPECIALOFFERID), TO_VARCHAR(ROWGUID))
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_LOAD
    WHERE _FILENAME = :V_LATEST_FILENAME;

    RETURN 'RAW refreshed from ' || V_LATEST_FILENAME;
END;
$$;


-- 9. SP initiate HISTORY
WITH col_meta AS (
    SELECT
        database_name,
        schema_name,
        table_name,

        /* (1) all business columns */
        LISTAGG(column_name, ',\n        ')
            WITHIN GROUP (ORDER BY ordinal_position) AS col_list,

        /* (2) select list from RAW */
        LISTAGG('R.' || column_name, ',\n        ')
            WITHIN GROUP (ORDER BY ordinal_position) AS select_col_list

    FROM ADVENTUREWORKS_RAW.CONTROL.RAW_TABLE_METADATA
    GROUP BY database_name, schema_name, table_name
)

SELECT
'CREATE OR REPLACE PROCEDURE ' || t.database_name || '.CONTROL.SP_' || t.table_name || '_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN ''HISTORY already initialized for ' || t.table_name || ''';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_HISTORY
    (
        ' || m.col_list || ',
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        ' || m.select_col_list || ',
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        ''9999-12-31'',
        TRUE,
        FALSE
    FROM ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || ' R;

    RETURN ''HISTORY initialized for ' || t.table_name || ''';
END;
$$;
' AS CREATE_SP_SQL
FROM ADVENTUREWORKS_RAW.CONTROL.TARGET_TABLE t
JOIN col_meta m
  ON t.database_name = m.database_name
 AND t.schema_name   = m.schema_name
 AND t.table_name    = m.table_name
ORDER BY t.schema_name, t.table_name;


-- 9.1. 
CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_PERSON_PERSON_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN 'HISTORY already initialized for PERSON_PERSON';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_HISTORY
    (
        BUSINESSENTITYID,
        PERSONTYPE,
        NAMESTYLE,
        TITLE,
        FIRSTNAME,
        MIDDLENAME,
        LASTNAME,
        SUFFIX,
        EMAILPROMOTION,
        ADDITIONALCONTACTINFO,
        DEMOGRAPHICS,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.BUSINESSENTITYID,
        R.PERSONTYPE,
        R.NAMESTYLE,
        R.TITLE,
        R.FIRSTNAME,
        R.MIDDLENAME,
        R.LASTNAME,
        R.SUFFIX,
        R.EMAILPROMOTION,
        R.ADDITIONALCONTACTINFO,
        R.DEMOGRAPHICS,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.DIM.PERSON_PERSON R;

    RETURN 'HISTORY initialized for PERSON_PERSON';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_PRODUCTION_PRODUCT_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN 'HISTORY already initialized for PRODUCTION_PRODUCT';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_HISTORY
    (
        PRODUCTID,
        NAME,
        PRODUCTNUMBER,
        MAKEFLAG,
        FINISHEDGOODSFLAG,
        COLOR,
        SAFETYSTOCKLEVEL,
        REORDERPOINT,
        STANDARDCOST,
        LISTPRICE,
        SIZE,
        SIZEUNITMEASURECODE,
        WEIGHTUNITMEASURECODE,
        WEIGHT,
        DAYSTOMANUFACTURE,
        PRODUCTLINE,
        CLASS,
        STYLE,
        PRODUCTSUBCATEGORYID,
        PRODUCTMODELID,
        SELLSTARTDATE,
        SELLENDDATE,
        DISCONTINUEDDATE,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.PRODUCTID,
        R.NAME,
        R.PRODUCTNUMBER,
        R.MAKEFLAG,
        R.FINISHEDGOODSFLAG,
        R.COLOR,
        R.SAFETYSTOCKLEVEL,
        R.REORDERPOINT,
        R.STANDARDCOST,
        R.LISTPRICE,
        R.SIZE,
        R.SIZEUNITMEASURECODE,
        R.WEIGHTUNITMEASURECODE,
        R.WEIGHT,
        R.DAYSTOMANUFACTURE,
        R.PRODUCTLINE,
        R.CLASS,
        R.STYLE,
        R.PRODUCTSUBCATEGORYID,
        R.PRODUCTMODELID,
        R.SELLSTARTDATE,
        R.SELLENDDATE,
        R.DISCONTINUEDDATE,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT R;

    RETURN 'HISTORY initialized for PRODUCTION_PRODUCT';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_CUSTOMER_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN 'HISTORY already initialized for SALES_CUSTOMER';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_HISTORY
    (
        CUSTOMERID,
        PERSONID,
        STOREID,
        TERRITORYID,
        ACCOUNTNUMBER,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.CUSTOMERID,
        R.PERSONID,
        R.STOREID,
        R.TERRITORYID,
        R.ACCOUNTNUMBER,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER R;

    RETURN 'HISTORY initialized for SALES_CUSTOMER';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESORDERDETAIL_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN 'HISTORY already initialized for SALES_SALESORDERDETAIL';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_HISTORY
    (
        SALESORDERID,
        SALESORDERDETAILID,
        CARRIERTRACKINGNUMBER,
        ORDERQTY,
        PRODUCTID,
        SPECIALOFFERID,
        UNITPRICE,
        UNITPRICEDISCOUNT,
        LINETOTAL,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.SALESORDERID,
        R.SALESORDERDETAILID,
        R.CARRIERTRACKINGNUMBER,
        R.ORDERQTY,
        R.PRODUCTID,
        R.SPECIALOFFERID,
        R.UNITPRICE,
        R.UNITPRICEDISCOUNT,
        R.LINETOTAL,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL R;

    RETURN 'HISTORY initialized for SALES_SALESORDERDETAIL';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESORDERHEADER_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN 'HISTORY already initialized for SALES_SALESORDERHEADER';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_HISTORY
    (
        SALESORDERID,
        REVISIONNUMBER,
        ORDERDATE,
        DUEDATE,
        SHIPDATE,
        STATUS,
        ONLINEORDERFLAG,
        SALESORDERNUMBER,
        PURCHASEORDERNUMBER,
        ACCOUNTNUMBER,
        CUSTOMERID,
        SALESPERSONID,
        TERRITORYID,
        BILLTOADDRESSID,
        SHIPTOADDRESSID,
        SHIPMETHODID,
        CREDITCARDID,
        CREDITCARDAPPROVALCODE,
        CURRENCYRATEID,
        SUBTOTAL,
        TAXAMT,
        FREIGHT,
        TOTALDUE,
        COMMENT,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.SALESORDERID,
        R.REVISIONNUMBER,
        R.ORDERDATE,
        R.DUEDATE,
        R.SHIPDATE,
        R.STATUS,
        R.ONLINEORDERFLAG,
        R.SALESORDERNUMBER,
        R.PURCHASEORDERNUMBER,
        R.ACCOUNTNUMBER,
        R.CUSTOMERID,
        R.SALESPERSONID,
        R.TERRITORYID,
        R.BILLTOADDRESSID,
        R.SHIPTOADDRESSID,
        R.SHIPMETHODID,
        R.CREDITCARDID,
        R.CREDITCARDAPPROVALCODE,
        R.CURRENCYRATEID,
        R.SUBTOTAL,
        R.TAXAMT,
        R.FREIGHT,
        R.TOTALDUE,
        R.COMMENT,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER R;

    RETURN 'HISTORY initialized for SALES_SALESORDERHEADER';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESTERRITORY_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN 'HISTORY already initialized for SALES_SALESTERRITORY';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_HISTORY
    (
        TERRITORYID,
        NAME,
        COUNTRYREGIONCODE,
        "GROUP",
        SALESYTD,
        SALESLASTYEAR,
        COSTYTD,
        COSTLASTYEAR,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.TERRITORYID,
        R.NAME,
        R.COUNTRYREGIONCODE,
        R."GROUP",
        R.SALESYTD,
        R.SALESLASTYEAR,
        R.COSTYTD,
        R.COSTLASTYEAR,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY R;

    RETURN 'HISTORY initialized for SALES_SALESTERRITORY';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SPECIALOFFER_INITIATE_HISTORY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_CNT INTEGER;
BEGIN

    /* Check if HISTORY already has data */
    SELECT COUNT(*)
    INTO :V_CNT
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_HISTORY;

    IF (V_CNT > 0) THEN
        RETURN 'HISTORY already initialized for SALES_SPECIALOFFER';
    END IF;

    /* Initial snapshot from RAW */
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_HISTORY
    (
        SPECIALOFFERID,
        DESCRIPTION,
        DISCOUNTPCT,
        TYPE,
        CATEGORY,
        STARTDATE,
        ENDDATE,
        MINQTY,
        MAXQTY,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.SPECIALOFFERID,
        R.DESCRIPTION,
        R.DISCOUNTPCT,
        R.TYPE,
        R.CATEGORY,
        R.STARTDATE,
        R.ENDDATE,
        R.MINQTY,
        R.MAXQTY,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER R;

    RETURN 'HISTORY initialized for SALES_SPECIALOFFER';
END;
$$;


-- 10. Create statement to create SP SCD 2
WITH meta AS (
    SELECT
        database_name,
        schema_name,
        table_name,
        pk_quality,

        /* (1) All columns */
        LISTAGG(column_name, ',\n        ')
            WITHIN GROUP (ORDER BY ordinal_position) AS col_list,

        /* (2) Select list with R. prefix */
        LISTAGG('R.' || column_name, ',\n        ')
            WITHIN GROUP (ORDER BY ordinal_position) AS select_col_list,

        /* (3) PK join condition */
        LISTAGG(
            CASE WHEN is_primary_key THEN 'H.' || column_name || ' = S.' || column_name END,
            ' AND '
        ) WITHIN GROUP (ORDER BY pk_ordinal_position) AS pk_join_cond,

        /* (4) PK join (source only) */
        LISTAGG(
            CASE WHEN is_primary_key THEN 'R.' || column_name || ' = H.' || column_name END,
            ' AND '
        ) WITHIN GROUP (ORDER BY pk_ordinal_position) AS pk_join_cond_raw,

        -- /* (5) HASH expression (non-PK) */
        -- 'HASH(' ||
        -- LISTAGG(
        --     CASE WHEN NVL(is_primary_key,FALSE)=FALSE THEN 'R.' || column_name END,
        --     ', '
        -- ) WITHIN GROUP (ORDER BY ordinal_position),
        -- || ')' AS hash_expr

        -- /* (6) PK_HASH expression */
        -- 'HASH(' ||
        -- LISTAGG(
        --     'TO_VARCHAR(R.' || column_name || ')',
        --     ', '
        -- ) WITHIN GROUP (ORDER BY pk_ordinal_position)
        -- FILTER (WHERE is_primary_key = TRUE)
        -- || ')' AS pk_hash_expr


    FROM ADVENTUREWORKS_RAW.CONTROL.RAW_TABLE_METADATA
    GROUP BY database_name, schema_name, table_name, pk_quality
)

SELECT
'CREATE OR REPLACE PROCEDURE ' || t.database_name || '.CONTROL.SP_' || t.table_name || '_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || ' R
    -- WHERE ' || m.pk_join_cond_raw || '
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_HISTORY
    (
        ' || m.col_list || ',
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        ' || m.select_col_list || ',
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        ''9999-12-31'',
        TRUE,
        FALSE
    FROM ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || ' R
    LEFT JOIN ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_HISTORY H
      -- ON ' || m.pk_join_cond_raw || '
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.' || SPLIT_PART(SPLIT_PART(m.pk_join_cond, ' = ', 1), '.', 2)
 || ' IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || '_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || ' R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ' || t.database_name || '.' || t.schema_name || '.' || t.table_name || ';

    RETURN ''SCD2 completed for ' || t.table_name || ''';
END;
$$;
' AS CREATE_SP_SQL
FROM TARGET_TABLE t
JOIN meta m
  ON t.database_name = m.database_name
 AND t.schema_name   = m.schema_name
 AND t.table_name    = m.table_name
WHERE m.pk_quality = 'OK'
ORDER BY t.schema_name, t.table_name;

-- 10.1 CREATE SP 

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_PERSON_PERSON_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ADVENTUREWORKS_RAW.DIM.PERSON_PERSON R
    -- WHERE R.BUSINESSENTITYID = H.BUSINESSENTITYID AND R.MIDDLENAME = H.MIDDLENAME AND R.ROWGUID = H.ROWGUID
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_HISTORY
    (
        BUSINESSENTITYID,
        PERSONTYPE,
        NAMESTYLE,
        TITLE,
        FIRSTNAME,
        MIDDLENAME,
        LASTNAME,
        SUFFIX,
        EMAILPROMOTION,
        ADDITIONALCONTACTINFO,
        DEMOGRAPHICS,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.BUSINESSENTITYID,
        R.PERSONTYPE,
        R.NAMESTYLE,
        R.TITLE,
        R.FIRSTNAME,
        R.MIDDLENAME,
        R.LASTNAME,
        R.SUFFIX,
        R.EMAILPROMOTION,
        R.ADDITIONALCONTACTINFO,
        R.DEMOGRAPHICS,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.DIM.PERSON_PERSON R
    LEFT JOIN ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_HISTORY H
      -- ON R.BUSINESSENTITYID = H.BUSINESSENTITYID AND R.MIDDLENAME = H.MIDDLENAME AND R.ROWGUID = H.ROWGUID
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.BUSINESSENTITYID IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ADVENTUREWORKS_RAW.DIM.PERSON_PERSON_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ADVENTUREWORKS_RAW.DIM.PERSON_PERSON R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ADVENTUREWORKS_RAW.DIM.PERSON_PERSON;

    RETURN 'SCD2 completed for PERSON_PERSON';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_PRODUCTION_PRODUCT_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT R
    -- WHERE R.PRODUCTID = H.PRODUCTID AND R.PRODUCTSUBCATEGORYID = H.PRODUCTSUBCATEGORYID AND R.PRODUCTMODELID = H.PRODUCTMODELID AND R.ROWGUID = H.ROWGUID
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_HISTORY
    (
        PRODUCTID,
        NAME,
        PRODUCTNUMBER,
        MAKEFLAG,
        FINISHEDGOODSFLAG,
        COLOR,
        SAFETYSTOCKLEVEL,
        REORDERPOINT,
        STANDARDCOST,
        LISTPRICE,
        SIZE,
        SIZEUNITMEASURECODE,
        WEIGHTUNITMEASURECODE,
        WEIGHT,
        DAYSTOMANUFACTURE,
        PRODUCTLINE,
        CLASS,
        STYLE,
        PRODUCTSUBCATEGORYID,
        PRODUCTMODELID,
        SELLSTARTDATE,
        SELLENDDATE,
        DISCONTINUEDDATE,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.PRODUCTID,
        R.NAME,
        R.PRODUCTNUMBER,
        R.MAKEFLAG,
        R.FINISHEDGOODSFLAG,
        R.COLOR,
        R.SAFETYSTOCKLEVEL,
        R.REORDERPOINT,
        R.STANDARDCOST,
        R.LISTPRICE,
        R.SIZE,
        R.SIZEUNITMEASURECODE,
        R.WEIGHTUNITMEASURECODE,
        R.WEIGHT,
        R.DAYSTOMANUFACTURE,
        R.PRODUCTLINE,
        R.CLASS,
        R.STYLE,
        R.PRODUCTSUBCATEGORYID,
        R.PRODUCTMODELID,
        R.SELLSTARTDATE,
        R.SELLENDDATE,
        R.DISCONTINUEDDATE,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT R
    LEFT JOIN ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_HISTORY H
      -- ON R.PRODUCTID = H.PRODUCTID AND R.PRODUCTSUBCATEGORYID = H.PRODUCTSUBCATEGORYID AND R.PRODUCTMODELID = H.PRODUCTMODELID AND R.ROWGUID = H.ROWGUID
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.PRODUCTID IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ADVENTUREWORKS_RAW.DIM.PRODUCTION_PRODUCT;

    RETURN 'SCD2 completed for PRODUCTION_PRODUCT';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_CUSTOMER_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER R
    -- WHERE R.CUSTOMERID = H.CUSTOMERID AND R.PERSONID = H.PERSONID AND R.STOREID = H.STOREID AND R.TERRITORYID = H.TERRITORYID AND R.ROWGUID = H.ROWGUID
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_HISTORY
    (
        CUSTOMERID,
        PERSONID,
        STOREID,
        TERRITORYID,
        ACCOUNTNUMBER,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.CUSTOMERID,
        R.PERSONID,
        R.STOREID,
        R.TERRITORYID,
        R.ACCOUNTNUMBER,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER R
    LEFT JOIN ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_HISTORY H
      -- ON R.CUSTOMERID = H.CUSTOMERID AND R.PERSONID = H.PERSONID AND R.STOREID = H.STOREID AND R.TERRITORYID = H.TERRITORYID AND R.ROWGUID = H.ROWGUID
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.CUSTOMERID IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_CUSTOMER;

    RETURN 'SCD2 completed for SALES_CUSTOMER';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESORDERDETAIL_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL R
    -- WHERE R.SALESORDERID = H.SALESORDERID AND R.SALESORDERDETAILID = H.SALESORDERDETAILID AND R.PRODUCTID = H.PRODUCTID AND R.SPECIALOFFERID = H.SPECIALOFFERID AND R.ROWGUID = H.ROWGUID
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_HISTORY
    (
        SALESORDERID,
        SALESORDERDETAILID,
        CARRIERTRACKINGNUMBER,
        ORDERQTY,
        PRODUCTID,
        SPECIALOFFERID,
        UNITPRICE,
        UNITPRICEDISCOUNT,
        LINETOTAL,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.SALESORDERID,
        R.SALESORDERDETAILID,
        R.CARRIERTRACKINGNUMBER,
        R.ORDERQTY,
        R.PRODUCTID,
        R.SPECIALOFFERID,
        R.UNITPRICE,
        R.UNITPRICEDISCOUNT,
        R.LINETOTAL,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL R
    LEFT JOIN ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_HISTORY H
      -- ON R.SALESORDERID = H.SALESORDERID AND R.SALESORDERDETAILID = H.SALESORDERDETAILID AND R.PRODUCTID = H.PRODUCTID AND R.SPECIALOFFERID = H.SPECIALOFFERID AND R.ROWGUID = H.ROWGUID
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.SALESORDERID IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERDETAIL;

    RETURN 'SCD2 completed for SALES_SALESORDERDETAIL';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESORDERHEADER_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER R
    -- WHERE R.SALESORDERID = H.SALESORDERID AND R.CUSTOMERID = H.CUSTOMERID AND R.SALESPERSONID = H.SALESPERSONID AND R.TERRITORYID = H.TERRITORYID AND R.BILLTOADDRESSID = H.BILLTOADDRESSID AND R.SHIPTOADDRESSID = H.SHIPTOADDRESSID AND R.SHIPMETHODID = H.SHIPMETHODID AND R.CREDITCARDID = H.CREDITCARDID AND R.CURRENCYRATEID = H.CURRENCYRATEID AND R.ROWGUID = H.ROWGUID
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_HISTORY
    (
        SALESORDERID,
        REVISIONNUMBER,
        ORDERDATE,
        DUEDATE,
        SHIPDATE,
        STATUS,
        ONLINEORDERFLAG,
        SALESORDERNUMBER,
        PURCHASEORDERNUMBER,
        ACCOUNTNUMBER,
        CUSTOMERID,
        SALESPERSONID,
        TERRITORYID,
        BILLTOADDRESSID,
        SHIPTOADDRESSID,
        SHIPMETHODID,
        CREDITCARDID,
        CREDITCARDAPPROVALCODE,
        CURRENCYRATEID,
        SUBTOTAL,
        TAXAMT,
        FREIGHT,
        TOTALDUE,
        COMMENT,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.SALESORDERID,
        R.REVISIONNUMBER,
        R.ORDERDATE,
        R.DUEDATE,
        R.SHIPDATE,
        R.STATUS,
        R.ONLINEORDERFLAG,
        R.SALESORDERNUMBER,
        R.PURCHASEORDERNUMBER,
        R.ACCOUNTNUMBER,
        R.CUSTOMERID,
        R.SALESPERSONID,
        R.TERRITORYID,
        R.BILLTOADDRESSID,
        R.SHIPTOADDRESSID,
        R.SHIPMETHODID,
        R.CREDITCARDID,
        R.CREDITCARDAPPROVALCODE,
        R.CURRENCYRATEID,
        R.SUBTOTAL,
        R.TAXAMT,
        R.FREIGHT,
        R.TOTALDUE,
        R.COMMENT,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER R
    LEFT JOIN ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_HISTORY H
      -- ON R.SALESORDERID = H.SALESORDERID AND R.CUSTOMERID = H.CUSTOMERID AND R.SALESPERSONID = H.SALESPERSONID AND R.TERRITORYID = H.TERRITORYID AND R.BILLTOADDRESSID = H.BILLTOADDRESSID AND R.SHIPTOADDRESSID = H.SHIPTOADDRESSID AND R.SHIPMETHODID = H.SHIPMETHODID AND R.CREDITCARDID = H.CREDITCARDID AND R.CURRENCYRATEID = H.CURRENCYRATEID AND R.ROWGUID = H.ROWGUID
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.SALESORDERID IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESORDERHEADER;

    RETURN 'SCD2 completed for SALES_SALESORDERHEADER';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SALESTERRITORY_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY R
    -- WHERE R.TERRITORYID = H.TERRITORYID AND R.ROWGUID = H.ROWGUID
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_HISTORY
    (
        TERRITORYID,
        NAME,
        COUNTRYREGIONCODE,
        "GROUP",
        SALESYTD,
        SALESLASTYEAR,
        COSTYTD,
        COSTLASTYEAR,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.TERRITORYID,
        R.NAME,
        R.COUNTRYREGIONCODE,
        R."GROUP",
        R.SALESYTD,
        R.SALESLASTYEAR,
        R.COSTYTD,
        R.COSTLASTYEAR,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY R
    LEFT JOIN ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_HISTORY H
      -- ON R.TERRITORYID = H.TERRITORYID AND R.ROWGUID = H.ROWGUID
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.TERRITORYID IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SALESTERRITORY;

    RETURN 'SCD2 completed for SALES_SALESTERRITORY';
END;
$$;

CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_SALES_SPECIALOFFER_SCD2()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    /* =========================================================
       1. CLOSE CHANGED RECORDS
       ========================================================= */
    
    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER R
    -- WHERE R.SPECIALOFFERID = H.SPECIALOFFERID AND R.ROWGUID = H.ROWGUID
    WHERE H.PK_HASH = R.PK_HASH
      AND H.IS_CURRENT = TRUE
      AND H.ROW_HASH <> R.ROW_HASH;

    /* =========================================================
       2. INSERT NEW + CHANGED
       ========================================================= */
    
    INSERT INTO ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_HISTORY
    (
        SPECIALOFFERID,
        DESCRIPTION,
        DISCOUNTPCT,
        TYPE,
        CATEGORY,
        STARTDATE,
        ENDDATE,
        MINQTY,
        MAXQTY,
        ROWGUID,
        MODIFIEDDATE,
        ROW_HASH,
        PK_HASH,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT,
        IS_DELETED
    )
    SELECT
        R.SPECIALOFFERID,
        R.DESCRIPTION,
        R.DISCOUNTPCT,
        R.TYPE,
        R.CATEGORY,
        R.STARTDATE,
        R.ENDDATE,
        R.MINQTY,
        R.MAXQTY,
        R.ROWGUID,
        R.MODIFIEDDATE,
        R.ROW_HASH,
        R.PK_HASH,
        CURRENT_TIMESTAMP(),
        '9999-12-31',
        TRUE,
        FALSE
    FROM ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER R
    LEFT JOIN ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_HISTORY H
      -- ON R.SPECIALOFFERID = H.SPECIALOFFERID AND R.ROWGUID = H.ROWGUID
      ON H.PK_HASH = R.PK_HASH
     AND H.IS_CURRENT = TRUE
    -- WHERE H.SPECIALOFFERID IS NULL
    WHERE H.PK_HASH IS NULL -- debug
       OR H.ROW_HASH <> R.ROW_HASH;


    /* =========================================================
       3. HANDLE DELETE
       ========================================================= */

    UPDATE ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER_HISTORY H
    SET
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        IS_CURRENT   = FALSE,
        IS_DELETED   = TRUE
    WHERE H.IS_CURRENT = TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER R
          WHERE H.PK_HASH = R.PK_HASH
      );

    /* =========================================================
       4. CLEAN RAW (OPTIONAL)
       ========================================================= */
    TRUNCATE TABLE ADVENTUREWORKS_RAW.FACT.SALES_SPECIALOFFER;

    RETURN 'SCD2 completed for SALES_SPECIALOFFER';
END;
$$;


-- 11. Create SP to create TASK
CREATE OR REPLACE PROCEDURE ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS(
    P_DATABASE   STRING,
    P_SCHEMA     STRING,
    P_TABLE      STRING,
    P_WAREHOUSE  STRING
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_TASK_PARENT      STRING;
    V_TASK_LOAD_RAW    STRING;
    V_TASK_INIT_HIST   STRING;
    V_TASK_SCD2        STRING;
    V_SQL              STRING;
BEGIN
    V_TASK_PARENT    := 'TASK_' || P_TABLE || '_REFRESH_PIPE';
    V_TASK_LOAD_RAW  := 'TASK_' || P_TABLE || '_LOAD_TO_RAW';
    V_TASK_INIT_HIST := 'TASK_' || P_TABLE || '_INITIATE_HISTORY';
    V_TASK_SCD2      := 'TASK_' || P_TABLE || '_SCD2';

    -- 1. Refresh PIPE (phụ thuộc vào TASK_MAIN_PIPE)
    V_SQL := '
    CREATE OR REPLACE TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_PARENT || '
      WAREHOUSE = ' || P_WAREHOUSE || '
      AFTER ' || P_DATABASE || '.CONTROL.TASK_MAIN_PIPE
    AS
    ALTER PIPE ' || P_DATABASE || '.' || P_SCHEMA || '.PIPE_' || P_TABLE || '_LOAD REFRESH;
    ';
    EXECUTE IMMEDIATE V_SQL;

    -- 2. LOAD → RAW
    V_SQL := '
    CREATE OR REPLACE TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_LOAD_RAW || '
      WAREHOUSE = ' || P_WAREHOUSE || '
      AFTER ' || P_DATABASE || '.CONTROL.' || V_TASK_PARENT || '
    AS
    CALL ' || P_DATABASE || '.CONTROL.SP_' || P_TABLE || '_FROM_LOAD_TO_RAW();
    ';
    EXECUTE IMMEDIATE V_SQL;

    -- 3. INIT HISTORY
    V_SQL := '
    CREATE OR REPLACE TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_INIT_HIST || '
      WAREHOUSE = ' || P_WAREHOUSE || '
      AFTER ' || P_DATABASE || '.CONTROL.' || V_TASK_LOAD_RAW || '
    AS
    CALL ' || P_DATABASE || '.CONTROL.SP_' || P_TABLE || '_INITIATE_HISTORY();
    ';
    EXECUTE IMMEDIATE V_SQL;

    -- 4. SCD2
    V_SQL := '
    CREATE OR REPLACE TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_SCD2 || '
      WAREHOUSE = ' || P_WAREHOUSE || '
      AFTER ' || P_DATABASE || '.CONTROL.' || V_TASK_INIT_HIST || ' -- debug
      -- AFTER ' || P_DATABASE || '.CONTROL.' || V_TASK_LOAD_RAW || ' -- debug
    AS
    CALL ' || P_DATABASE || '.CONTROL.SP_' || P_TABLE || '_SCD2();
    ';
    EXECUTE IMMEDIATE V_SQL;

    -- 5. Resume các task con
    EXECUTE IMMEDIATE 'ALTER TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_PARENT || ' RESUME';
    EXECUTE IMMEDIATE 'ALTER TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_LOAD_RAW || ' RESUME';
    EXECUTE IMMEDIATE 'ALTER TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_INIT_HIST || ' RESUME'; -- debug
    EXECUTE IMMEDIATE 'ALTER TASK ' || P_DATABASE || '.CONTROL.' || V_TASK_SCD2 || ' RESUME';

    RETURN 'Per-table TASK chain created for ' || P_TABLE || ' (PIPE after TASK_MAIN_PIPE).';
END;
$$;

-- 11.1. Generate CALL statement 
SELECT
    'CALL ' || DATABASE_NAME || '.CONTROL.SP_CREATE_INGESTION_TASKS(''' 
           || DATABASE_NAME || ''',''' 
           || SCHEMA_NAME   || ''',''' 
           || TABLE_NAME    || ''',''COMPUTE_WH'');' AS CALL_SQL
FROM TARGET_TABLE;

-- 11.2. CALL SP 
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_MAIN_PIPE SUSPEND;
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS('ADVENTUREWORKS_RAW','DIM','PERSON_PERSON','COMPUTE_WH');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS('ADVENTUREWORKS_RAW','DIM','PRODUCTION_PRODUCT','COMPUTE_WH');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS('ADVENTUREWORKS_RAW','FACT','SALES_CUSTOMER','COMPUTE_WH');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS('ADVENTUREWORKS_RAW','FACT','SALES_SALESORDERDETAIL','COMPUTE_WH');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS('ADVENTUREWORKS_RAW','FACT','SALES_SALESORDERHEADER','COMPUTE_WH');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS('ADVENTUREWORKS_RAW','FACT','SALES_SALESTERRITORY','COMPUTE_WH');
CALL ADVENTUREWORKS_RAW.CONTROL.SP_CREATE_INGESTION_TASKS('ADVENTUREWORKS_RAW','FACT','SALES_SPECIALOFFER','COMPUTE_WH');
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_MAIN_PIPE RESUME;

-- 12. Create Task Main
-- 12.1. Check task refresh pipe 
SHOW TASKS LIKE 'TASK_%_REFRESH_PIPE' IN SCHEMA CONTROL;
-- 12.2. Query create SP main pipe
CREATE OR REPLACE TASK ADVENTUREWORKS_RAW.CONTROL.TASK_MAIN_PIPE
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON */3 * * * * UTC'
AS
SELECT 1;

ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_MAIN_PIPE RESUME;

-- 12.3. Query to get statement to resume all task refresh pipe 
SELECT
'ALTER TASK '
|| database_name || '.CONTROL.TASK_' || table_name
|| '_REFRESH_PIPE RESUME;'
AS RESUME_TASK_SQL
FROM TARGET_TABLE
ORDER BY table_name;

-- 12.4. Resume all task refresh pipe
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_MAIN_PIPE SUSPEND;

ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_PERSON_PERSON_REFRESH_PIPE RESUME;
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_PRODUCTION_PRODUCT_REFRESH_PIPE RESUME;
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_SALES_CUSTOMER_REFRESH_PIPE RESUME;
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_SALES_SALESORDERDETAIL_REFRESH_PIPE RESUME;
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_SALES_SALESORDERHEADER_REFRESH_PIPE RESUME;
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_SALES_SALESTERRITORY_REFRESH_PIPE RESUME;
ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_SALES_SPECIALOFFER_REFRESH_PIPE RESUME;

ALTER TASK ADVENTUREWORKS_RAW.CONTROL.TASK_MAIN_PIPE RESUME;

-- 13. Run task main to test full flow
EXECUTE TASK ADVENTUREWORKS_RAW.CONTROL.TASK_MAIN_PIPE;
